name: 'RegEx check'
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1/2'
env: 
  WOOCOMERCE_KEY: ${{ secrets.WOOCOMERCE_KEY }}
  WOOCOMERCE_SECRET: ${{ secrets.WOOCOMERCE_SECRET }}
  WOOCOMERCE_HOST: ${{ secrets.WOOCOMERCE_HOST }}
  USER: ${{ secrets.USER }}
  PASS: ${{ secrets.PASS }}
  FTP_PASS: ${{ secrets.FTP_PASS }}
  FTP_USER: ${{ secrets.FTP_USER }}
jobs:
  main:
    runs-on: ubuntu-latest
    name: main
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      name: price_crapper
      with:
        python-version: '3.13' 
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run : python app.py
  offer_scrapper:

    runs-on: ubuntu-latest
    name: offer_scrapper
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      name: offer_scrapper
      with:
        python-version: '3.13' 
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run : python app.py
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          dist

