name: 'RegEx check'
on: [push]
env: 
  WOOCOMERCE_KEY: ${{ secrests.WOOCOMERCE_KEY }}
  WOOCOMERCE_SECRET: ${{ secrests.WOOCOMERCE_SECRET }}
  WOOCOMERCE_HOST: ${{ secrests.WOOCOMERCE_HOST }}
  USER: ${{ secrests.USER }}
  PASS: ${{ secrests.PASS }}
  FTP_PASS: ${{ secrests.FTP_PASS }}
  FTP_USER: ${{ secrests.FTP_USER }}
jobs:
  main:
    runs-on: ubuntu-latest
    name: main
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run : python app.py
